//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAs.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentFile
    {
        public long AssignmentFileId { get; set; }
        public string Name { get; set; }
        public string Extension { get; set; }
        public byte[] Data { get; set; }
        public long FK_SubjectAssignment { get; set; }
    
        public virtual SubjectAssignment SubjectAssignment { get; set; }
    }
}
